name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs_on: "ubuntu-20.04"
    steps:
      - name: "Install Python 3.11"
        uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with: 
          python-version: "3.11"
