name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Install Python 3.11"
        uses: "actions/checkout@v3"
      - name: "Setup Python 3.11"
        uses: "actions/setup-python@v4"
        with: 
          python-version: "3.11.2"
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install venv and Install requirements
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      - name: Run pytest
        run: pytest -s -v
      - name: Run pylint
        run: pylint src
